FROM alpine
RUN 	apk update && \
	apk add nodejs && \
	mkdir -p /app
COPY ./repo/todo-angular-express /app/
COPY ./config.js /app/
RUN cd /app && npm install
EXPOSE 3000
CMD ["/usr/bin/node", "/app/app.js"]
